### ISSUE TITLE
OpenCM 9.04 model for circuit design programs

### ISSUE THREAD

**Issue by Y-Grigoriy** [ROBOTIS-GIT/OpenCM9.04#103]
Hello,

I saw pictures of the OpenCM connection with different devices in manual (e.g. https://emanual.robotis.com/assets/images/parts/controller/opencm904/sdcard_bb.png). It looks like scheme drawn in program for electrical circuit drawing (e.g. Fritzing). Do you have the file with OpenCM model (may be .fzpz for Fritzing)? If yes, could you share it?

**Comment by ROBOTIS-Will** [comment]
Hi @Y-Grigoriy 
I've found the Fritzing file, but it didn't contain any circuitry information.
In case you need schematics and other information about the board, please refer to the OpenCM9.04 eManual below.
https://emanual.robotis.com/docs/en/parts/controller/opencm904/#downloads
Thank you.

**Comment by Y-Grigoriy** [comment]
Hi @ROBOTIS-Will 
If this file contains good image of OpenCM in svg format, it also be helpful. I can supplement this file by necessary schemes by myself. What about Dynamixel servomotors as parts for Fritzing?

**Comment by ROBOTIS-Will** [comment]
Let me see if I can find and share any meaningful data from what I found.
Unfortunately, I don't see any DYNAMIXEL in this project.

**Comment by Y-Grigoriy** [comment]
@ROBOTIS-Will Do I right understand, that you couldn't find any data?

**Comment by ROBOTIS-Will** [comment]
@Y-Grigoriy 
I only found .svg files for OpenCM9.04 and XL-320.
I'll upload them here just in case you need them.
[robotis_fritzing.zip](https://github.com/ROBOTIS-GIT/OpenCM9.04/files/6240218/robotis_fritzing.zip)
Thanks!

**Comment by Y-Grigoriy** [comment]
@ROBOTIS-Will thank you!
