### ISSUE TITLE
EEPROM library problem

### ISSUE THREAD

**Issue by leoxbox** [ROBOTIS-GIT/OpenCM9.04#12]
The EEPROM library is not working. I tried the simple "write" and "read" example, but board is not responding after downloading the example on it.

**Comment by chcbaram** [comment]
Did you try Examples->OpenCM9.04->Etc->EEPROM ? 
When I checked again, it worked well.

**Comment by leoxbox** [comment]
Hi,
Sorry, it was a problem with the length of the data I stored in the EEPROM. Because it was more than 2KB...  👍 
Thanks.
