### ISSUE TITLE
[openCM IDE]: I can not communicate with OPENCM9.04

### ISSUE THREAD

**Issue by ar-msb** [ROBOTIS-GIT/OpenCM9.04#17]
Hi again,
I used opencm9.04 and it was fine, but from this afternoon I can not cammunicate with it. I can not even upload a blink program on it. on arduino IDE it says :
![image](https://user-images.githubusercontent.com/35629121/35878025-4026cfde-0b8c-11e8-9f4f-0a68d45e1fd0.png)
and on openCM IDE it says:
![image](https://user-images.githubusercontent.com/35629121/35878069-6f6d7888-0b8c-11e8-8f24-53ed4a61ba5d.png)
My computer finds ROBOTIS virtual com ports.
Can anyone help me please?

**Comment by OpusK** [comment]
Hi, @ar-msb 

First of all, please check if you are using COM port in serial monitor, etc.
If COMPORT is free and this problem persists, try downloading again via [recovery mode](http://emanual.robotis.com/docs/en/parts/controller/opencm904/#recovery-mode).

**Comment by ar-msb** [comment]
@OpusK 
Thanks. I used the recovery mode, and fortuantely, the board is fine now.
