### ISSUE TITLE
[OpenCM9.04]: interrupt pins

### ISSUE THREAD

**Issue by ar-msb** [ROBOTIS-GIT/OpenCM9.04#18]
Hi,
I was trying to program OpenCM9.04 using OPENCM IDE. I am wondering which pins can be attached to an interrupt. Any information regarding this matter would be appreciated.
I want to read an encoder pulses with this board to avoid serial communication with other boards, and then command a certain speed to AX12+, so I need 2 interrupts at least.

**Comment by OpusK** [comment]
Hi, @ar-msb 

You can get the information at [wikipage](https://github.com/ROBOTIS-GIT/OpenCM9.04/wiki/Hardware_Specification#pin-function-definition).
The last values are the EXTI numbers.
