### ISSUE TITLE
Problem with installation of library (OpenCM) for Arduino

### ISSUE THREAD

**Issue by GrigoriyAY** [ROBOTIS-GIT/OpenCM9.04#48]
I added link in preferences, but when I opened boards manager, I couldn't download library for OpenCM9.04 and I got the message (attached screenshot). PC: Windows 10 and Arduino IDE 1.8.7. Could you help me with this problem?
![error of opencm library](https://user-images.githubusercontent.com/22524348/47368002-81e82980-d6e9-11e8-83c0-9d26f768fd64.PNG)

**Comment by OpusK** [comment]
Hi, @GrigoriyAY 

Would you like to try again with the instructions below?
- [E-manual](http://emanual.robotis.com/docs/en/parts/controller/opencm904/#development-environment)

**Comment by OpusK** [comment]
@GrigoriyAY 

Sorry for my late reply.

> Could you suggest how to manually place the library for OpenCM in the necessary folders?
I think there was something about this in the Arduino official document, but I can not find it now...

As an alternative, please refer to the link below.
 - [HOWTO : Adding multiple OpenCR boards to the Arduino IDE](https://community.robotsource.org/t/howto-adding-multiple-opencr-boards-to-the-arduino-ide/1497)

In this case, it is necessary to set things related to tools separately, but there is no official guide related to this.

**Comment by OpusK** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
