### ISSUE TITLE
Is it possible to program barebones on this board without IDE? 

### ISSUE THREAD

**Issue by Le0nX** [ROBOTIS-GIT/OpenCM9.04#51]
Hello! My question is: is it possible to program this board barebones? For example, if I want to  start my OS on it?

**Comment by Le0nX** [comment]
Hey?

**Comment by OpusK** [comment]
Hi, @Le0nX 

Sorry for late reply.
Because this board is low-end, it can not run a normal OS. It would be possible to have an optimized embedded OS, but generally we do not use the OS on this board.

**Comment by Le0nX** [comment]
Ok! And how I can flash my openCM board (without robotis IDE) to start running my optimized OS?

**Comment by Le0nX** [comment]
Thanks! Can I do it via USB or jtag is needed ?

**Comment by OpusK** [comment]
Both are possible.
Since OpenCM 9.04 uses ST's chip, you will find the information associated with it and use that method
(ex: USB: dfu, JTAG: ST-LINK)

**Comment by OpusK** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by Ash-S** [comment]
Hi, how can i flash an application to openCM904 without using arduino/openCM IDE ? Is there any way, please suggest! Thanks!
