### ISSUE TITLE
Dynamixel Workbench: PRO+ Issues

### ISSUE THREAD

**Issue by RobotisBrandon** [ROBOTIS-GIT/OpenCM9.04#71]
Users are reporting that the DYNAMIXEL Workbench library, when used with OpenCM9.04 + Arduino IDE, does not properly change the Profile Acceleration when a jointeMode instruction is used for DXL PRO+.

> The value '1000' should go to the acceleration registry, but it doesn't take.
> 
> The work around is to add a second line:
> 
> servo.jointMode(servoID[1], 2920, 1000);
> servo.itemWrite(servoID[1], "Profile_Acceleration", 1495, &log);

**Comment by RyanJaehyunShim** [comment]
@RobotisBrandon 

The bug has been fixed. It should work fine now. Let us know if you run into any other problems.

Regards,
Ryan
