### ISSUE TITLE
vibration

### ISSUE THREAD

**Issue by unverciftci** [ROBOTIS-GIT/OpenCM9.04#74]
I have 6 xl320 with opencm 904c. when the motors are connected some are vibrating and slightly moving. why is that do you think? thanks.

**Comment by OpusK** [comment]
> I have 6 xl320 with opencm 904c. when the motors are connected some are vibrating and slightly moving. why is that do you think? thanks.

Is there a separate code running? Or is it just a power supply and is there something like that?

In the latter case, it may be a problem related to Dynamixel. Therefore, we recommend that you test Dynamixel itself and if you have any problems, please raise an issue in the ROBOTIS Forum.

**Comment by OpusK** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
