### ISSUE TITLE
Can't unlock the stm32f103

### ISSUE THREAD

**Issue by Le0nX** [ROBOTIS-GIT/OpenCM9.04#76]
@OpusK, Hi! When I'm trying to flash the stm32f103 on the opencm 9.04 board via st-link, openocd gets an error:
```
Info : device id = 0x20036410
Info : flash size = 128kbytes
Error: stm32x device protected
Error: failed erasing sectors 0 to 2
```
I've tried `stm32f1x unlock 0` but it didn't help...

**Comment by Le0nX** [comment]
![image](https://user-images.githubusercontent.com/10488862/56823561-ec2a8400-685c-11e9-8e80-9f5182615478.png)

**Comment by Le0nX** [comment]
I'm using STLINK-V2 & SW4STM32 IDE + openocd

**Comment by Le0nX** [comment]
I've used stm utils for windows and it has solved the problem. After it had unlocked and erased the chip you can flash it under linux...

**Comment by Le0nX** [comment]
Still don't understand why openocd doesn't want to unlock some of opecm's mem sectors...

**Comment by TuxLeon** [comment]
Could it be related to the version of your ST-Link Utility like in this
post?
https://community.st.com/s/question/0D50X00009XkWyMSAV/stlink-utility-mass-flash-erase-fails-however-erase-bank-1-and-2-works


Am Mo., 29. Apr. 2019 um 10:45 Uhr schrieb Le0nX <notifications@github.com>:

**Comment by Le0nX** [comment]
@TuxLeon, do you mean ST-Link Utility under linux? 
ST-Link Utility for Windows does it's job very well: unlocks and erases/flashes the chip.
The problem was with linux version. Under linux I couldn't unlock and erase the chip. Now, after I've done this under windows, I can flash the unlocked chip under linux.

**Comment by TuxLeon** [comment]
Yes. Perhaps just try an other version of openOcd under Linux.

Am Mo., 29. Apr. 2019 um 11:08 Uhr schrieb Le0nX <notifications@github.com>:
