### ISSUE TITLE
barebones USART3 corrupts data at 1mbit

### ISSUE THREAD

**Issue by Le0nX** [ROBOTIS-GIT/OpenCM9.04#81]
I've got an issue with comunicating with AX-12a trough USART3. When a baud rate is 115200 get the right data, but when I change the baud to 1mbit(for ax-12a) then I get corrupted data...

**Comment by Le0nX** [comment]
If I want to send data to EXP 485 board from opencm 9.04 and my ax-12a is connected to this EXP board, do I need to do it via USART1 or USART3?

**Comment by Le0nX** [comment]
I've fixed the problem. Everything is working great with FreeRTOS running on Opencm 9.04 with EXP board connected.

**Comment by Iervolino458** [comment]
Hello, how did you manage to communicate the motors connected in the EXP board to the OpenCM usb?

**Comment by Le0nX** [comment]
Hi, @Iervolino458! Nope. The ax-12a motors are connected to EXP board via UART(TTL), not via USB. So I'm sending commands to servos from Opencm 9.04 connected to EXP board trough USART3.
