### ISSUE TITLE
Communication problem with OpenCM9.04 via ArduinoIDE

### ISSUE THREAD

**Issue by mkdy** [ROBOTIS-GIT/OpenCM9.04#85]
Hello,

I've installed ArduinoIDE on my Ubuntu laptop and connected OpenCM9.04 board to it via USB. So, I'm able to run BlinkLED sketch and green LED really blinks. However, when I'm trying to run Serial_HelloWorld sketch, I see it is uploaded and says "Go Application", but I find neither counts nor any errors in terminal.

Here is the full terminal output:
```
Sketch uses 34232 bytes (29%) of program storage space. Maximum is 116736 bytes.
Global variables use 8644 bytes of dynamic memory.
Enter bootloader
stm32ld ver 1.0.1
OpenCM Download Ver 1.0.4 2015.06.16 
Board Name : CM-904
Ready To download 
Flash : 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
Write Size : 34520
CheckSum : Success..
Go Application
```

Any ideas why that happens?

I'm using ArduinoIDE 1.8.9 with OpenCM9.04 driver v.1.4.1 if that matters.

**Comment by jawad-tech** [comment]
Have you opened you SERIAL monitor after the program is uploaded successfully. Because When i execute the Position control, the motor doesn't rotate, but When i open the SERIAL monitor after the program is uploaded, the motors start to rotate.

**Comment by OpusK** [comment]
Hi, @mkdy 

The above terminal logs are normal.
Serial example is to output data in Serial, so check with Serial Monitor.

It is normal for the Arduino IDE terminal not to output any other data.

**Comment by mkdy** [comment]
@jawad-tech @OpusK Thanks for the responses!
Indeed, when I open Serial Monitor, I see Hello-World messages. However, I have to change port from /dev/ttyACM0 to /dev/ttyACM1 manually before opening Serial Monitor (otherwise Serial Monitor would not open, and that's weird).
At the moment I'm trying to start Dynamixel XL430 servo, but with no success. FindDynamixels sketch says that no devices are found. XL430 is powered via 12v5a power supply. Any ideas?

**Comment by jawad-tech** [comment]
1) First When you connect the usb from Controller to pc, you will check in ubuntu terminal 'lsusb` command to see your Controller IS connected to Which port. because Sometime there is a bug in an arduino port. 
also try to make the port permissions by
'sudo chmod 777 /dev/ttyACMx  Where x is your connected port.


and one other thing If you are using arduino IDE to Run the Code Its Ok, 
Please check the SERIAL settings
+ If using OPENCM Controller SERIAL bus1
+ If using OPENCM and rs485 board then serIal  bus3 
+If open cr then SERIAL bus2

check your Connections of dynamixel to Controller or U2D2

**Comment by OpusK** [comment]
@mkdy 

Did you upload or reset the firmware with Serial Monitor open?
If so, it can be changed to a different name (eg. ACM1) by avoiding the device name already in use.

When uploading a reset or a sketch file, close the serial monitor window.

**Comment by OpusK** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
