### ISSUE TITLE
Support all of the Arduino installs - Now including ARM64

### ISSUE THREAD

**Issue by KurtE** [ROBOTIS-GIT/OpenCM9.04#89]
Now that Arduino has released official installations for Arm64 installs, it would be great of Robotis supplied packages for the board installs that run on these platforms.

That issue has come up recently on the Trossen Robotics forum: http://forums.trossenrobotics.com/showthread.php?16001-Open-CM9-04-Anyone-had-luck-programming-using-the-Arduno-IDE&p=95621#post95621

Likewise for OpenCR.

**Comment by KyoungHwan2046** [comment]
Hi, @KurtE  
I will check about this issue.
Thank you.
