### ISSUE TITLE
Conflict with wire.h

### ISSUE THREAD

**Issue by PlusOneOptics** [ROBOTIS-GIT/OpenCM9.04#91]
Hi everyone,

I'm using the OpenCM 9.04 with the expansion board 485.

I'm using 3 MX-106 servos and a MPU9250 for a project.

In any case, I have managed to communicate with the MPU9250 with the wire.h method.

However, this causes an issue. When I used the readbyte function, the servos no longer responds to the any dxl_wb commands. except dxl_wb.init. however it will still cause a failure on the board after a few seconds of usage.

// -------------------
_void readBytes(uint8_t address, uint8_t subAddress, uint8_t count, uint8_t * dest)
{  
  Wire.beginTransmission(address);   // Initialize the Tx buffer
  Wire.write(subAddress);            // Put slave register address in Tx buffer
  Wire.endTransmission(false);       // Send the Tx buffer, but send a restart to keep connection alive
  uint8_t i = 0;
        Wire.requestFrom(address, count);  // Read bytes from slave register address 
  while (Wire.available()) {
        dest[i++] = Wire.read(); }         // Put read results in the Rx buffer
}_
// ----------------------

The MPU is using pin 18 and 22. Which I believe avoids any of the native pins, (TXDs, RXDs, MISO, etc)

Could someone point out what I'm missing?

**Comment by KyoungHwan2046** [comment]
Hi, @PlusOneOptics 
Could you let me know how did you use readBytes function with dxl_wb command on your code and how did you setting the board on your code?
