### ISSUE TITLE
Bootloader source

### ISSUE THREAD

**Issue by mkleox** [ROBOTIS-GIT/OpenCM9.04#97]
Hi,

We use the open cm9.04 board in our project and there are some problems that cause in the boot time. I want to know if it's possible to have the boot loader source that we can change it accordingly. I believe this project is open source and also the bootloader source can be release with the community.

ROBOTIS is the best :)

Thank you and best regards,
Leox

**Comment by ROBOTIS-Will** [comment]
Hi Leox,

Thank you for your support and interest in ROBOTIS.
Unfortunately, our bootloader source code is protected and cannot be shared to the public.
If you can describe the issue regarding the boot time, I'll review it with our developers and see if we can fix it for you or at least may be able to suggest other solutions.
Thank you very much.
