### ISSUE TITLE
Can't connect to MCU with ST-LINK/V2 and ST-LINK Utility

### ISSUE THREAD

**Issue by LeTo37** [ROBOTIS-GIT/OpenCM9.04#99]
Hi there,

I'm sure I am doing something wrong but I would really appreciate a bit of help on this. 

I am simply trying to connect to the OpenCM9 with ST-Link Utility. My hardware connection is as advised on the Robotis website:
![image](https://user-images.githubusercontent.com/43195586/101534347-9be23600-395c-11eb-997c-b86039901b2f.png)

I have separately powered the CM9 with 5V.

No matter what target settings I change, I consistently cannot connect to the board:
![image](https://user-images.githubusercontent.com/43195586/101541767-79a1e580-3967-11eb-8df0-50fdb7334787.png)

Any ideas?

Thank you in advance!

**Comment by ROBOTIS-Will** [comment]
Hi @LeTo37 
I just tried with my OpenCM9.04 and ST-Link/V2 based on the connection from the eManual, but couldn't find the problem(memory is protected by default)
![image](https://user-images.githubusercontent.com/26239359/101567132-9dbb0080-3a13-11eb-9deb-2bd6485e091d.png)
Please be aware when you program the device with ST-Link, it will erase the bootloader section which cannot be recovered as well as void the warranty.
Thank you.

**Comment by LeTo37** [comment]
Hi Will,

Thank you so much for your quick response! I really appreciate it, especially given the ST-Link has nothing to do with ROBOTIS.

I managed to solve my issue with a slightly different connection to that shown in the eManual (shown below). By holding the reset button down while connecting and choosing "Connect Under Reset" in my Target settings, I managed to establish a connection.
![20201209_130956](https://user-images.githubusercontent.com/43195586/101676043-3a839b00-3a20-11eb-84de-70364d571caf.jpg)

**Comment by ROBOTIS-Will** [comment]
Oh, thank you for the updates!
We'll release a new product very soon that works with Arduino MKR(which is as small as OpenCM9.04), and you might also want to [check it out](https://emanual.robotis.com/docs/en/parts/interface/mkr_shield/).
